// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Audio_screen_init(void)
{
ui_Audio = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Audio, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_VUMeter0 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter0, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter0, -100,100);
lv_bar_set_value(ui_VUMeter0,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter0, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter0, 30);
lv_obj_set_height( ui_VUMeter0, lv_pct(50));
lv_obj_set_y( ui_VUMeter0, 0 );
lv_obj_set_x( ui_VUMeter0, lv_pct(-40) );
lv_obj_set_align( ui_VUMeter0, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter0, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter0, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter1 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter1, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter1, -100,100);
lv_bar_set_value(ui_VUMeter1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter1, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter1, 30);
lv_obj_set_height( ui_VUMeter1, lv_pct(75));
lv_obj_set_y( ui_VUMeter1, 0 );
lv_obj_set_x( ui_VUMeter1, lv_pct(-30) );
lv_obj_set_align( ui_VUMeter1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter1, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter2 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter2, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter2, -100,100);
lv_bar_set_value(ui_VUMeter2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter2, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter2, 30);
lv_obj_set_height( ui_VUMeter2, lv_pct(85));
lv_obj_set_y( ui_VUMeter2, 0 );
lv_obj_set_x( ui_VUMeter2, lv_pct(-20) );
lv_obj_set_align( ui_VUMeter2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter2, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter3 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter3, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter3, -100,100);
lv_bar_set_value(ui_VUMeter3,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter3, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter3, 30);
lv_obj_set_height( ui_VUMeter3, lv_pct(95));
lv_obj_set_y( ui_VUMeter3, 0 );
lv_obj_set_x( ui_VUMeter3, lv_pct(-10) );
lv_obj_set_align( ui_VUMeter3, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter3, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter4 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter4, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter4, -100,100);
lv_bar_set_value(ui_VUMeter4,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter4, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter4, 30);
lv_obj_set_height( ui_VUMeter4, lv_pct(100));
lv_obj_set_align( ui_VUMeter4, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter4, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter5 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter5, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter5, -100,100);
lv_bar_set_value(ui_VUMeter5,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter5, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter5, 30);
lv_obj_set_height( ui_VUMeter5, lv_pct(95));
lv_obj_set_y( ui_VUMeter5, 0 );
lv_obj_set_x( ui_VUMeter5, lv_pct(10) );
lv_obj_set_align( ui_VUMeter5, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter5, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter6 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter6, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter6, -100,100);
lv_bar_set_value(ui_VUMeter6,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter6, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter6, 30);
lv_obj_set_height( ui_VUMeter6, lv_pct(85));
lv_obj_set_y( ui_VUMeter6, 0 );
lv_obj_set_x( ui_VUMeter6, lv_pct(20) );
lv_obj_set_align( ui_VUMeter6, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter6, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter6, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter7 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter7, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter7, -100,100);
lv_bar_set_value(ui_VUMeter7,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter7, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter7, 30);
lv_obj_set_height( ui_VUMeter7, lv_pct(75));
lv_obj_set_y( ui_VUMeter7, 0 );
lv_obj_set_x( ui_VUMeter7, lv_pct(30) );
lv_obj_set_align( ui_VUMeter7, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter7, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter7, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VUMeter8 = lv_bar_create(ui_Audio);
lv_bar_set_mode(ui_VUMeter8, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_VUMeter8, -100,100);
lv_bar_set_value(ui_VUMeter8,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_VUMeter8, -25, LV_ANIM_OFF);
lv_obj_set_width( ui_VUMeter8, 30);
lv_obj_set_height( ui_VUMeter8, lv_pct(50));
lv_obj_set_y( ui_VUMeter8, 0 );
lv_obj_set_x( ui_VUMeter8, lv_pct(40) );
lv_obj_set_align( ui_VUMeter8, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VUMeter8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VUMeter8, lv_color_hex(0x037BFC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VUMeter8, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_AudioButton = lv_btn_create(ui_Audio);
lv_obj_set_width( ui_AudioButton, lv_pct(100));
lv_obj_set_height( ui_AudioButton, lv_pct(100));
lv_obj_set_align( ui_AudioButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AudioButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AudioButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AudioButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AudioButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Audio, ui_event_Audio, LV_EVENT_ALL, NULL);

}
