// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Images_screen_init(void)
{
ui_Images = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Images, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HexCorp = lv_img_create(ui_Images);
lv_img_set_src(ui_HexCorp, &ui_img_hexcorp360_png);
lv_obj_set_width( ui_HexCorp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HexCorp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HexCorp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HexCorp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HexCorp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CPU = lv_img_create(ui_Images);
lv_img_set_src(ui_CPU, &ui_img_cpu360_png);
lv_obj_set_width( ui_CPU, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CPU, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CPU, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CPU, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CPU, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BRK = lv_img_create(ui_Images);
lv_img_set_src(ui_BRK, &ui_img_brk360_png);
lv_obj_set_width( ui_BRK, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BRK, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BRK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BRK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BRK, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Hive = lv_img_create(ui_Images);
lv_img_set_src(ui_Hive, &ui_img_hive360_png);
lv_obj_set_width( ui_Hive, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Hive, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Hive, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Hive, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Hive, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HAL9000 = lv_img_create(ui_Images);
lv_img_set_src(ui_HAL9000, &ui_img_hal9000_png);
lv_obj_set_width( ui_HAL9000, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HAL9000, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HAL9000, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HAL9000, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HAL9000, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spiral = lv_img_create(ui_Images);
lv_img_set_src(ui_Spiral, &ui_img_spiral360_png);
lv_obj_set_width( ui_Spiral, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Spiral, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Spiral, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Spiral, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Spiral, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagesButton = lv_btn_create(ui_Images);
lv_obj_set_width( ui_ImagesButton, lv_pct(100));
lv_obj_set_height( ui_ImagesButton, lv_pct(100));
lv_obj_set_align( ui_ImagesButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ImagesButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ImagesButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ImagesButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Images, ui_event_Images, LV_EVENT_ALL, NULL);

}
