// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Options_screen_init(void)
{
ui_Options = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Options, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Options);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 0 );
lv_obj_set_y( ui_Label7, lv_pct(10) );
lv_obj_set_align( ui_Label7, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label7,"Options");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Container_1 = lv_obj_create(ui_Options);
lv_obj_remove_style_all(ui_Option_Container_1);
lv_obj_set_height( ui_Option_Container_1, 50);
lv_obj_set_width( ui_Option_Container_1, lv_pct(70));
lv_obj_set_y( ui_Option_Container_1, -50 );
lv_obj_set_x( ui_Option_Container_1, lv_pct(10) );
lv_obj_set_align( ui_Option_Container_1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Option_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Option_1 = lv_checkbox_create(ui_Option_Container_1);
lv_checkbox_set_text(ui_Option_1,"");
lv_obj_set_width( ui_Option_1, lv_pct(60));
lv_obj_set_height( ui_Option_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Option_1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Option_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Option_1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Label_1 = lv_label_create(ui_Option_Container_1);
lv_obj_set_width( ui_Option_Label_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Option_Label_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Option_Label_1, 50 );
lv_obj_set_y( ui_Option_Label_1, 0 );
lv_obj_set_align( ui_Option_Label_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Option_Label_1,"Option 1");
lv_obj_set_style_text_align(ui_Option_Label_1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Option_Label_1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Container_3 = lv_obj_create(ui_Options);
lv_obj_remove_style_all(ui_Option_Container_3);
lv_obj_set_height( ui_Option_Container_3, 50);
lv_obj_set_width( ui_Option_Container_3, lv_pct(70));
lv_obj_set_y( ui_Option_Container_3, 50 );
lv_obj_set_x( ui_Option_Container_3, lv_pct(10) );
lv_obj_set_align( ui_Option_Container_3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Option_Container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Option_3 = lv_checkbox_create(ui_Option_Container_3);
lv_checkbox_set_text(ui_Option_3,"");
lv_obj_set_width( ui_Option_3, lv_pct(60));
lv_obj_set_height( ui_Option_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Option_3, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Option_3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Option_3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Label_3 = lv_label_create(ui_Option_Container_3);
lv_obj_set_width( ui_Option_Label_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Option_Label_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Option_Label_3, 50 );
lv_obj_set_y( ui_Option_Label_3, 0 );
lv_obj_set_align( ui_Option_Label_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Option_Label_3,"Option 3");
lv_obj_set_style_text_align(ui_Option_Label_3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Option_Label_3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Container_4 = lv_obj_create(ui_Options);
lv_obj_remove_style_all(ui_Option_Container_4);
lv_obj_set_height( ui_Option_Container_4, 50);
lv_obj_set_width( ui_Option_Container_4, lv_pct(70));
lv_obj_set_y( ui_Option_Container_4, 100 );
lv_obj_set_x( ui_Option_Container_4, lv_pct(10) );
lv_obj_set_align( ui_Option_Container_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Option_Container_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Option_4 = lv_checkbox_create(ui_Option_Container_4);
lv_checkbox_set_text(ui_Option_4,"");
lv_obj_set_width( ui_Option_4, lv_pct(60));
lv_obj_set_height( ui_Option_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Option_4, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Option_4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Option_4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Option_Label_4 = lv_label_create(ui_Option_Container_4);
lv_obj_set_width( ui_Option_Label_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Option_Label_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Option_Label_4, 50 );
lv_obj_set_y( ui_Option_Label_4, 0 );
lv_obj_set_align( ui_Option_Label_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Option_Label_4,"Option 4");
lv_obj_set_style_text_align(ui_Option_Label_4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Option_Label_4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Brightness_Slider = lv_slider_create(ui_Options);
lv_slider_set_value( ui_Brightness_Slider, 40, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Brightness_Slider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Brightness_Slider, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Brightness_Slider, 25);
lv_obj_set_width( ui_Brightness_Slider, lv_pct(90));
lv_obj_set_align( ui_Brightness_Slider, LV_ALIGN_CENTER );


ui_Label8 = lv_label_create(ui_Options);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Brightness");
lv_obj_add_flag( ui_Label8, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_Label8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Option_1, ui_event_Option_1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Option_3, ui_event_Option_3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Option_4, ui_event_Option_4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Brightness_Slider, ui_event_Brightness_Slider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Options, ui_event_Options, LV_EVENT_ALL, NULL);

}
