// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Power_screen_init(void)
{
ui_Power = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Power, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Power);
lv_obj_set_width( ui_Label1, lv_pct(40));
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, lv_pct(-25) );
lv_obj_set_y( ui_Label1, lv_pct(-30) );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Battery:");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery_Level = lv_label_create(ui_Power);
lv_obj_set_width( ui_Battery_Level, lv_pct(40));
lv_obj_set_height( ui_Battery_Level, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Battery_Level, lv_pct(20) );
lv_obj_set_y( ui_Battery_Level, lv_pct(-30) );
lv_obj_set_align( ui_Battery_Level, LV_ALIGN_CENTER );
lv_label_set_text(ui_Battery_Level,"100%\n3.3mv");
lv_obj_set_style_text_align(ui_Battery_Level, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Battery_Level, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Power);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, lv_pct(-11) );
lv_obj_set_align( ui_Label3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label3,"Press & Hold\nto sleep");
lv_obj_add_flag( ui_Label3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0x037BFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Label3, lv_color_hex(0x037BFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Label3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sleep_Timer = lv_label_create(ui_Power);
lv_obj_set_width( ui_Sleep_Timer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sleep_Timer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sleep_Timer, 0 );
lv_obj_set_y( ui_Sleep_Timer, lv_pct(-5) );
lv_obj_set_align( ui_Sleep_Timer, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sleep_Timer,"Long-press this button\nto wake up");
lv_obj_set_style_text_align(ui_Sleep_Timer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Sleep_Timer, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Power, ui_event_Power, LV_EVENT_ALL, NULL);

}
