// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Images
void ui_Images_screen_init(void);
void ui_event_Images( lv_event_t * e);
lv_obj_t *ui_Images;
lv_obj_t *ui_HexCorp;
lv_obj_t *ui_CPU;
lv_obj_t *ui_BRK;
lv_obj_t *ui_Hive;
lv_obj_t *ui_HAL9000;
lv_obj_t *ui_Spiral;
lv_obj_t *ui_ImagesButton;
// CUSTOM VARIABLES


// SCREEN: ui_Audio
void ui_Audio_screen_init(void);
void ui_event_Audio( lv_event_t * e);
lv_obj_t *ui_Audio;
lv_obj_t *ui_VUMeter0;
lv_obj_t *ui_VUMeter1;
lv_obj_t *ui_VUMeter2;
lv_obj_t *ui_VUMeter3;
lv_obj_t *ui_VUMeter4;
lv_obj_t *ui_VUMeter5;
lv_obj_t *ui_VUMeter6;
lv_obj_t *ui_VUMeter7;
lv_obj_t *ui_VUMeter8;
lv_obj_t *ui_AudioButton;
// CUSTOM VARIABLES


// SCREEN: ui_Options
void ui_Options_screen_init(void);
void ui_event_Options( lv_event_t * e);
lv_obj_t *ui_Options;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Option_Container_1;
void ui_event_Option_1( lv_event_t * e);
lv_obj_t *ui_Option_1;
lv_obj_t *ui_Option_Label_1;
lv_obj_t *ui_Option_Container_3;
void ui_event_Option_3( lv_event_t * e);
lv_obj_t *ui_Option_3;
lv_obj_t *ui_Option_Label_3;
lv_obj_t *ui_Option_Container_4;
void ui_event_Option_4( lv_event_t * e);
lv_obj_t *ui_Option_4;
lv_obj_t *ui_Option_Label_4;
void ui_event_Brightness_Slider( lv_event_t * e);
lv_obj_t *ui_Brightness_Slider;
lv_obj_t *ui_Label8;
// CUSTOM VARIABLES


// SCREEN: ui_Power
void ui_Power_screen_init(void);
void ui_event_Power( lv_event_t * e);
lv_obj_t *ui_Power;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Battery_Level;
void ui_event_Label3( lv_event_t * e);
lv_obj_t *ui_Label3;
lv_obj_t *ui_Sleep_Timer;
// CUSTOM VARIABLES


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
lv_obj_t *ui_Splash;
lv_obj_t *ui_Label5;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_brk[1] = {&ui_img_brk360_png};
const lv_img_dsc_t *ui_imgset_cpu[1] = {&ui_img_cpu360_png};
const lv_img_dsc_t *ui_imgset_hal[1] = {&ui_img_hal9000_png};
const lv_img_dsc_t *ui_imgset_hexcorp[1] = {&ui_img_hexcorp360_png};
const lv_img_dsc_t *ui_imgset_hive[1] = {&ui_img_hive360_png};
const lv_img_dsc_t *ui_imgset_spiral[1] = {&ui_img_spiral360_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Images( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoNextImage_cb( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoPreviousImage_cb( e );
}
}

void ui_event_Audio( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoNextImage_cb( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoPreviousImage_cb( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoOptionsScreen_cb( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      gotoPowerScreen_cb( e );
}
}

void ui_event_Options( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      exitOptionsScreen_cb( e );
}
}

void ui_event_Option_1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option1_ON_cb( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option1_OFF_cb( e );
}
}

void ui_event_Option_3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option3_ON_cb( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option3_OFF_cb( e );
}
}

void ui_event_Option_4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option4_ON_cb( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      option4_OFF_cb( e );
}
}

void ui_event_Brightness_Slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      setBrightness_cb( e );
}
}

void ui_event_Power( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      exitPowerScreen_cb( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      exitPowerScreen_cb( e );
}
}

void ui_event_Label3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      gotoSleepButtonPressed_cb( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      gotoSleepButtonReleased_cb( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Images_screen_init();
ui_Audio_screen_init();
ui_Options_screen_init();
ui_Power_screen_init();
ui_Splash_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Images);
}
