// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Images
void ui_Images_screen_init(void);
void ui_event_Images( lv_event_t * e);
extern lv_obj_t *ui_Images;
extern lv_obj_t *ui_HexCorp;
extern lv_obj_t *ui_CPU;
extern lv_obj_t *ui_BRK;
extern lv_obj_t *ui_Hive;
extern lv_obj_t *ui_HAL9000;
extern lv_obj_t *ui_Spiral;
extern lv_obj_t *ui_ImagesButton;
// CUSTOM VARIABLES

// SCREEN: ui_Audio
void ui_Audio_screen_init(void);
void ui_event_Audio( lv_event_t * e);
extern lv_obj_t *ui_Audio;
extern lv_obj_t *ui_VUMeter0;
extern lv_obj_t *ui_VUMeter1;
extern lv_obj_t *ui_VUMeter2;
extern lv_obj_t *ui_VUMeter3;
extern lv_obj_t *ui_VUMeter4;
extern lv_obj_t *ui_VUMeter5;
extern lv_obj_t *ui_VUMeter6;
extern lv_obj_t *ui_VUMeter7;
extern lv_obj_t *ui_VUMeter8;
extern lv_obj_t *ui_AudioButton;
// CUSTOM VARIABLES

// SCREEN: ui_Options
void ui_Options_screen_init(void);
void ui_event_Options( lv_event_t * e);
extern lv_obj_t *ui_Options;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Option_Container_1;
void ui_event_Option_1( lv_event_t * e);
extern lv_obj_t *ui_Option_1;
extern lv_obj_t *ui_Option_Label_1;
extern lv_obj_t *ui_Option_Container_3;
void ui_event_Option_3( lv_event_t * e);
extern lv_obj_t *ui_Option_3;
extern lv_obj_t *ui_Option_Label_3;
extern lv_obj_t *ui_Option_Container_4;
void ui_event_Option_4( lv_event_t * e);
extern lv_obj_t *ui_Option_4;
extern lv_obj_t *ui_Option_Label_4;
void ui_event_Brightness_Slider( lv_event_t * e);
extern lv_obj_t *ui_Brightness_Slider;
extern lv_obj_t *ui_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_Power
void ui_Power_screen_init(void);
void ui_event_Power( lv_event_t * e);
extern lv_obj_t *ui_Power;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Battery_Level;
void ui_event_Label3( lv_event_t * e);
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Sleep_Timer;
// CUSTOM VARIABLES

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_Label5;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_hexcorp360_png);   // assets/HexCorp360.png
LV_IMG_DECLARE( ui_img_cpu360_png);   // assets/CPU360.png
LV_IMG_DECLARE( ui_img_brk360_png);   // assets/BRK360.png
LV_IMG_DECLARE( ui_img_hive360_png);   // assets/hive360.png
LV_IMG_DECLARE( ui_img_hal9000_png);   // assets/HAL9000.png
LV_IMG_DECLARE( ui_img_spiral360_png);   // assets/spiral360.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
