// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ImageReleased_cb(lv_event_t * e)
{
	// Your code here
}

void ScreenPressed_cb(lv_event_t * e)
{
	// Your code here
}

void ScreenReleased_cb(lv_event_t * e)
{
	// Your code here
}

void CompassClicked_cb(lv_event_t * e)
{
	// Your code here
}

void ScreenLongTouch_cb(lv_event_t * e)
{
	// Your code here
}

void ScreenVeryLongTouch_cb(lv_event_t * e)
{
	// Your code here
}

void ScreenShortClicked_cb(lv_event_t * e)
{
	// Your code here
}

void bleRadioToggle_cb(lv_event_t * e)
{
	// Your code here
}

void bleDeviceStatus_cb(lv_event_t * e)
{
	// Your code here
}

void gotoNextImage_cb(lv_event_t * e)
{
	// Your code here
}

void gotoPreviousImage_cb(lv_event_t * e)
{
	// Your code here
}

void gotoOptionsScreen_cb(lv_event_t * e)
{
	// Your code here
}

void gotoPowerScreen_cb(lv_event_t * e)
{
	// Your code here
}

void exitOptionsScreen_cb(lv_event_t * e)
{
	// Your code here
}

void exitPowerScreen_cb(lv_event_t * e)
{
	// Your code here
}

void gotoSleepButtonPressed_cb(lv_event_t * e)
{
	// Your code here
}

void gotoSleepButtonReleased_cb(lv_event_t * e)
{
	// Your code here
}

void option1_ON_cb(lv_event_t * e)
{
	// Your code here
}

void option1_OFF_cb(lv_event_t * e)
{
	// Your code here
}

void option3_ON_cb(lv_event_t * e)
{
	// Your code here
}

void option3_OFF_cb(lv_event_t * e)
{
	// Your code here
}

void option4_ON_cb(lv_event_t * e)
{
	// Your code here
}

void option4_OFF_cb(lv_event_t * e)
{
	// Your code here
}

void setBrightness_cb(lv_event_t * e)
{
	// Your code here
}
