// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void gotoNextImage_cb(lv_event_t * e);
void gotoPreviousImage_cb(lv_event_t * e);
void gotoOptionsScreen_cb(lv_event_t * e);
void gotoPowerScreen_cb(lv_event_t * e);
void exitOptionsScreen_cb(lv_event_t * e);
void option1_ON_cb(lv_event_t * e);
void option1_OFF_cb(lv_event_t * e);
void option3_ON_cb(lv_event_t * e);
void option3_OFF_cb(lv_event_t * e);
void option4_ON_cb(lv_event_t * e);
void option4_OFF_cb(lv_event_t * e);
void setBrightness_cb(lv_event_t * e);
void exitPowerScreen_cb(lv_event_t * e);
void gotoSleepButtonPressed_cb(lv_event_t * e);
void gotoSleepButtonReleased_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
